#
# Cookbook Name:: common_servers
# Recipe:: default
#

template "/data/nginx/common/servers.conf" do
  owner node[:owner_name]
  group node[:owner_name]
  mode 0644
  source "servers.conf.erb"
  variables({
    :client_max_body_size => node[:common_servers][:client_max_body_size],
    :use_verb_whitelist => node[:common_servers][:http_white_list][:enabled],
    :whitelisted_verbs => (node[:common_servers][:http_white_list][:accepted_verbs] || []).join("|")

  })
end

file "/data/nginx/common/keep.servers.conf" do
  owner node[:owner_name]
  group node[:owner_name]
  mode 0644
  content '# Do not edit this file'
end
